export const DEMO_COUNT = 'DEMO_COUNT';
export const RESET_COUNT = 'RESET_COUNT';
export const SHOW_AUDIT = 'SHOW_AUDIT';
export const QUERY_ATTRIBUTE = 'QUERY_ATTRIBUTE';
export const GET_TABLE_META = 'GET_TABLE_META';
export const RECEIEVE_ATTRIBUTE = 'RECEIEVE_ATTRIBUTE';
export const ATTRIBUTE_PAGEMETA = 'ATTRIBUTE_PAGEMETA';
export const CATEGORY_ATTRIBUTE_EDIT_TEST_ACTION = 'CATEGORY_ATTRIBUTE_EDIT_TEST_ACTION';
export const GET_CLASSIFICATION = 'GET_CLASSIFICATION';
export const UPDATE_CURRENT_CLASSIFICATION = 'UPDATE_CURRENT_CLASSIFICATION';
export const SHOW_CURRENT_CLASSIFICATION = 'SHOW_CURRENT_CLASSIFICATION';
export const UNLINK_CLASSIFICATION = 'UNLINK_CLASSIFICATION';
export const UNLINK_ATTEIBUTE= 'UNLINK_ATTEIBUTE';
export const CLEANUP_CLASSIFICATION= 'CLEANUP_CLASSIFICATION';
export const QUERY_CLASSIFICATION= 'QUERY_CLASSIFICATION';
export const REFRESH_CLASSIFICATION= 'REFRESH_CLASSIFICATION';
export const CLEANUP_CLASSIFICATION_RESULT= 'CLEANUP_CLASSIFICATION_RESULT';
export const BIND_CLASSIFICATION= 'BIND_CLASSIFICATION';
export const RECEIVE_CATEGORY_ATTRIBUTE = 'RECEIVE_CATEGORY_ATTRIBUTE';
export const CLEANUP_CATEGORY_ATTRIBUTE = 'CLEANUP_CATEGORY_ATTRIBUTE';
export const BIND_CATEGORY_ATTRIBUTE = 'BIND_CATEGORY_ATTRIBUTE';
export const DELETE_ATTEIBUTE = 'DELETE_ATTEIBUTE';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';





