

export default {
	categoryAttribute: {resource:"/category/retrieveCategory" ,method:'get'},
	classificationList: {resource:"/category/queryClassification" ,method:'get'},
	attributeList: {resource:"/category/categoryAttribute" ,method:'get'},
	productInfo: {resource:"/fsproduct/searchProductInfo" ,method:'post'},
	productPackage: {resource:"/findProductPackageList" ,method:'post'},
	productPrice: {resource:"/productprice/searchProductPrice" ,method:'post'},
	priceSetting: {resource:"/systemConfig/save" ,method:'get'},
	productPriceCheck: {resource:"/findWaitApprovingProductPriceList" ,method:'get'},
	productPricePlan: {resource:"*" ,method:'get'},
	productPublish: {resource:"/publishinfo/search" ,method:'post'},
	productPriceChange: {resource:"/priceVoucher/search" ,method:'post'},
	displayCategory: {resource:"/category/retrieveDisplayCategory" ,method:'get'},
	displayProduct: {resource:"/productForDisplayCategory/search" ,method:'post'},
	producShelf: {resource:"/productShelf/findProductList" ,method:'post'},
	operatorProduct: {resource:"/operatorProduct/searchOperatorProduct" ,method:'post'},
	orderTimeSetting: {resource:"/fsorder/getOrderExpiredList" ,method:'get'},
	orderRecalculation: {resource:"/deliveryCostRule/searchDeliveryCostRuleBySeller" ,method:'get'},
	freightTemplate: {resource:"/deliveryCostRule/searchDeliveryCostRuleBySeller" ,method:'get'},
	orderList: {resource:"/fsorder/searchOrder" ,method:'post'},
	orderListRefund: {resource:"/fsorder/searchRefund" ,method:'post'},
	orderListReturn: {resource:"/fsorder/searchReturn" ,method:'post'},
	orderListReplace: {resource:"/fsorder/searchReplacement" ,method:'post'},
	orderListRepair: {resource:"/fsorder/searchRepair" ,method:'post'},
	logicStock: {resource:"/stockManagement/searchLogicStockList" ,method:'post'},
	stockLevel: {resource:"/stockManagement/search" ,method:'post'},
	logicStockRule: {resource:"/stockAllocationRule/search" ,method:'post'},
	warehouseList: {resource:"/warehouse/getWarehouseList" ,method:'post'},
	deliveryRange: {resource:"/warehouse/getDistributionAreaInfoList" ,method:'post'},
	supplierPriority: {resource:"/fssupplier/searchRuleInfo" ,method:'post'},
	channelStock: {resource:"/stockByChannel/search" ,method:'post'},
	stockFreezeRecord: {resource:"/stockFreeze/searchFreezeRecord" ,method:'post'},
	stockFreeze: {resource:"/stockFreeze/searchReceipt" ,method:'post'},
	stockFreezeCreate: {resource:"/stockFreeze/pageMeta" ,method:'get'},
	promotionList: {resource:"/promotionManage/searchPromotions" ,method:'post'},
	bDiscountList: {resource:"*" ,method:'get'},
	dDiscountDistribution: {resource:"/dDiscountAllocation/searchDDiscountAmountAllocations" ,method:'post'},
	proportionList: {resource:"/promotionManage/searchProductProportion" ,method:'post'},
	appointmentList: {resource:"/preReserveManage/searchReservations" ,method:'post'},
	prepaidList: {resource:"/preStoreManage/searchPreStores" ,method:'post'},
	couponList: {resource:"/voucherManage/searchVouchers" ,method:'post'},
	couponGenerate: {resource:"/voucherManage/searchGeneratedVouchers" ,method:'post'},
	couponDistributeList: {resource:"/voucherManage/searchIssuedVouchers" ,method:'post'},
	memberImport: {resource:"/fsMember/uploadFsmemberDatas" ,method:'post'},
	memberInfo: {resource:"/fsMember/searchFsMemberList" ,method:'post'},
	employeeList: {resource:"/fsEmployee/findStoreEmployeeDetail" ,method:'get'},
	channelList: {resource:"/fsChannel/searchFSChannelListPage" ,method:'post'},
	storeList: {resource:"/fsPointOfService/initQuryStoreListSelect" ,method:'get'},
	adminRegion: {resource:"/region/searchFsAdminRegionList" ,method:'post'},
	salesRegion: {resource:"/fsArea/searchFsAreaList" ,method:'post'},
	salesBranch:  {resource:"/fsBusOrg/searchBusOrgList" ,method:'post'},

	categoryAttributeEdit: {resource:"/category/categoryClassification" ,method:'get'},
	productDetail:{resource:"/fsproduct/productInfoDetail" ,method:'get'},
	logicStockRuleEdit: {resource:"/stockAllocationRule/modify" ,method:'get'},
	productDetailEdit:  {resource:"/fsproduct/productInfoDetail" ,method:'get'},
	deliveryRangeEdit: {resource:"/warehouse/getDistributionAreaInfoList" ,method:'post'},
	supplierPriorityEdit:  {resource:"/fssupplier/retrieveRule" ,method:'get'},
	stockFreezeRecordDetail: {resource:"/stockFreeze/searchSpecificFreezeRecord" ,method:'get'},
	stockFreezeDetail:{resource:"/stockFreeze/searchReceiptProduct" ,method:'get'},
	orderDetail:{resource:"/fsorder/getOrderDetail" ,method:'get'},
	orderDetailReturn:{resource:"/fsorder/getReturnDetail" ,method:'get'},
	orderDetailReplace:{resource:"/fsorder/getReplacementDetail" ,method:'get'},
	orderDetailRepair:{resource:"/fsorder/getRepairDetail" ,method:'get'},
	orderDetailRefund:{resource:"/fsorder/getRefundDetail" ,method:'get'},
	memberDetail:{resource:"/fsMember/searchFsMemberDetail" ,method:'post'},
	promotionOrderList:{resource:"/fsorder/getOrdersByPromotionCode" ,method:'get'},
	employeeCoupon:{resource:"/fsMember/findVouchersPageByEmployee" ,method:'post'},
	createBDiscount:{resource:"/promotionManage/saveBDiscount" ,method:'post'},
	displayBDiscount:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createDDiscount:{resource:"/promotionManage/saveDDiscount" ,method:'post'},
	displayDDiscount:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createPurchaseGift:{resource:"/promotionManage/saveAddFreeProductRule" ,method:'post'},
	displayPurchaseGift:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createPurchaseCoupon:{resource:"/promotionManage/saveAddVoucherRule" ,method:'post'},
	displayPurchaseCoupon:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createPurchaseCredit:{resource:"/promotionManage/savePurchaseCreditRule" ,method:'post'},
	displayPurchaseCredit:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createConditionDiscount:{resource:"/promotionManage/saveOrderFullDiscount" ,method:'post'},
	displayConditionDiscount:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createConditionCoupon:{resource:"/promotionManage/saveAddVoucherOrderFullRule" ,method:'post'},
	displayConditionCoupon:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createConditionFreight: {resource:"/promotionManage/saveFreeDelivery" ,method:'post'},
	displayConditionFreight: {resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	//createConditionGift: {resource:"/promotionManage/saveAchieveThresholdGift" ,method:'post'},   for wave 2
	displayConditionGift: {resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createConditionCredit: {resource:"/promotionManage/saveConditionCreditRule" ,method:'post'},
	displayConditionCredit: {resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createCreditDouble: {resource:"/promotionManage/savePointMultiple" ,method:'post'},
	displayCreditDouble: {resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	createProductGroup: {resource:"/promotionManage/saveBundleProducts" ,method:'post'},
	displayProductGroup: {resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	appointmentCreate: {resource:"/preReserveManage/savePreReserveActivity" ,method:'post'},
	appointmentDisplay: {resource:"/preReserveManage/searchReservations" ,method:'post'},
	prepaidCreate: {resource:"/preStoreManage/savePreStoreActivity" ,method:'post'},
	prepaidDisplay: {resource:"/preStoreManage/searchPreStores" ,method:'post'},
	couponCreate: {resource:"/voucherManage/saveVoucher" ,method:'post'},
	couponDisplay: {resource:"/voucherManage/searchVouchers" ,method:'post'},
	couponDistribute: {resource:"/voucherManage/searchGeneratedVouchers" ,method:'post'},
	createDiscount:{resource:"/promotionManage/saveDirectlyDiscount" ,method:'post'},
	displayDiscount:{resource:"/promotionManage/displayPromotionInfo" ,method:'get'},
	stockLog:{resource:"/stockLog/search" ,method:'post'},
	stockFreezeRecordDetail:{resource:"/stockFreeze/searchSpecificFreezeRecord" ,method:'get'},
	employeeCoupon:{resource:"/fsEmployee/findVouchersPageByEmployee" ,method:'post'},
	warehouseStore:{resource:"/fspossetting/getpossetting" ,method:'post'},
	supplierPriorityEdit:{resource:"/fssupplier/createRule" ,method:'post'},
	promotionOrderList:{resource:"/fsorder/getOrdersByPromotionCode" ,method:'get'},
	commentList:{resource:"/review/search" ,method:'post'}
};
